# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iK5nTcP4_tqXr7BRVZQH7PGsrMm5ORKF
"""

from google.colab import files
uploaded = files.upload()

import zipfile

with zipfile.ZipFile("archive.zip", "r") as z:
    z.extractall("data")
    print(z.namelist())

import pandas as pd

df = pd.read_csv("data/global_placement.csv")
df.head()

rows, columns = df.shape
print("Rows:", rows)
print("Columns:", columns)

df.info()

df["placement_status"].value_counts()

df.groupby("placement_status")["salary"].describe()

print("Duplicate rows:", df.duplicated().sum())
df.describe()

for col in ["college_tier", "country", "university_ranking_band", "specialization", "industry"]:
    print(f"--- {col} ---")
    print(df[col].value_counts())
    print()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import (
    accuracy_score, classification_report, ConfusionMatrixDisplay,
    mean_absolute_error, r2_score
)

RANDOM_STATE = 42
sns.set_theme(style="whitegrid", palette="Set2")

# Encode target for classification: Placed = 1, Not Placed = 0
df["placement_label"] = df["placement_status"].map({"Placed": 1, "Not Placed": 0})

# Salary subset: only students who were actually placed
df_placed = df[df["placement_status"] == "Placed"].copy()

print("Full dataset shape:", df.shape)
print("Placed-only subset shape:", df_placed.shape)

categorical_cols = ["college_tier", "country", "university_ranking_band", "specialization", "industry"]

df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)
df_placed_encoded = pd.get_dummies(df_placed, columns=categorical_cols, drop_first=True)

print(df_encoded.shape)
print(df_placed_encoded.columns.tolist())

# Features for placement model: drop the raw text status, the label, and salary
# (salary would leak information about placement, so it must NOT be a feature here)
X_placement = df_encoded.drop(columns=["placement_status", "placement_label", "salary"])
y_placement = df_encoded["placement_label"]

X_train, X_test, y_train, y_test = train_test_split(
    X_placement, y_placement, test_size=0.2, random_state=RANDOM_STATE, stratify=y_placement
)

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)

placement_model = RandomForestClassifier(
    n_estimators=200,
    random_state=RANDOM_STATE,
    n_jobs=-1
)

placement_model.fit(X_train, y_train)

placement_predictions = placement_model.predict(X_test)
placement_accuracy = accuracy_score(y_test, placement_predictions)

print(f"Placement model accuracy: {placement_accuracy:.2%}")

# Baseline: what if the model just always guessed the majority class?
baseline_accuracy = max(y_test.mean(), 1 - y_test.mean())
print(f"Baseline (always guess majority class): {baseline_accuracy:.2%}")

print("\nClassification Report:")
print(classification_report(y_test, placement_predictions))

fig, ax = plt.subplots(figsize=(6, 6))

ConfusionMatrixDisplay.from_predictions(
    y_test,
    placement_predictions,
    display_labels=["Not Placed", "Placed"],
    cmap="Blues",
    colorbar=False,
    ax=ax
)

ax.set_title("Confusion Matrix — Placement Model")
plt.tight_layout()
plt.show()

importance = pd.Series(
    placement_model.feature_importances_,
    index=X_placement.columns
).sort_values(ascending=False)

plt.figure(figsize=(8, 6))
importance.head(10).sort_values().plot(kind="barh", color="#2a9d8f")
plt.title("Top 10 Feature Importances — Placement Model")
plt.xlabel("Relative importance")
plt.tight_layout()
plt.show()

print(importance.head(10))

X_salary = df_placed_encoded.drop(columns=["placement_status", "placement_label", "salary"])
y_salary = df_placed_encoded["salary"]

X_train_s, X_test_s, y_train_s, y_test_s = train_test_split(
    X_salary, y_salary, test_size=0.2, random_state=RANDOM_STATE
)

print("Train shape:", X_train_s.shape)
print("Test shape:", X_test_s.shape)

salary_model = RandomForestRegressor(
    n_estimators=200,
    random_state=RANDOM_STATE,
    n_jobs=-1
)

salary_model.fit(X_train_s, y_train_s)

salary_predictions = salary_model.predict(X_test_s)

mae = mean_absolute_error(y_test_s, salary_predictions)
r2 = r2_score(y_test_s, salary_predictions)

print(f"Mean Absolute Error: {mae:.2f}")
print(f"R² Score: {r2:.4f}")

avg_salary = y_test_s.mean()
error_percentage = (mae / avg_salary) * 100

print(f"Average salary in test set: {avg_salary:.2f}")
print(f"MAE as % of average salary: {error_percentage:.2f}%")

salary_importance = pd.Series(
    salary_model.feature_importances_,
    index=X_salary.columns
).sort_values(ascending=False)

print(salary_importance.head(10))

def predict_student_outcome(student_dict):
    """
    Takes a dictionary of student details and returns:
    - placement prediction (Placed / Not Placed)
    - placement probability
    - predicted salary (only if placed)
    """
    # Convert input into a one-row DataFrame
    new_df = pd.DataFrame([student_dict])

    # One-hot encode the same way as training data
    new_df_encoded = pd.get_dummies(new_df, columns=categorical_cols)

    # --- Placement prediction ---
    # Align columns with training data (fill missing dummy columns with 0)
    new_df_placement = new_df_encoded.reindex(columns=X_placement.columns, fill_value=0)

    placement_pred = placement_model.predict(new_df_placement)[0]
    placement_proba = placement_model.predict_proba(new_df_placement)[0][1]  # probability of "Placed"

    result = {
        "placement_prediction": "Placed" if placement_pred == 1 else "Not Placed",
        "placement_probability": round(placement_proba * 100, 2)
    }

    # --- Salary prediction (only if placed) ---
    if placement_pred == 1:
        new_df_salary = new_df_encoded.reindex(columns=X_salary.columns, fill_value=0)
        salary_pred = salary_model.predict(new_df_salary)[0]
        result["predicted_salary"] = round(salary_pred, 2)
    else:
        result["predicted_salary"] = None

    return result

sample_student = {
    "cgpa": 8.2,
    "backlogs": 0,
    "college_tier": "Tier 1",
    "country": "USA",
    "university_ranking_band": "Top 100",
    "internship_count": 3,
    "aptitude_score": 78,
    "communication_score": 82,
    "specialization": "AI/ML",
    "industry": "Tech",
    "internship_quality_score": 7.5
}

result = predict_student_outcome(sample_student)
print(result)

sample_student = {
    "cgpa": 8.2,
    "backlogs": 0,
    "college_tier": "Tier 1",
    "country": "USA",
    "university_ranking_band": "Top 100",
    "internship_count": 3,
    "aptitude_score": 78,
    "communication_score": 82,
    "specialization": "AI/ML",
    "industry": "Tech",
    "internship_quality_score": 7.5
}

result = predict_student_outcome(sample_student)
print(result)

import joblib

joblib.dump(placement_model, "placement_model.pkl")
joblib.dump(salary_model, "salary_model.pkl")
joblib.dump(X_placement.columns.tolist(), "placement_columns.pkl")
joblib.dump(X_salary.columns.tolist(), "salary_columns.pkl")
joblib.dump(categorical_cols, "categorical_cols.pkl")

print("Models and columns saved.")